### ISSUE TITLE
Not really and Issue but wondering about the interface

### ISSUE THREAD

**Issue by ricandersonva** [jarmoruuth/AutoIntegrate#31]
Jarmo, 
Still loving your script which to me has become the goto interface for Pixinsight processing.

I have a question about the window. I have 2 displays where one is large and the main place where Pix displays and runs. The other is smaller and a totally different resolution which does not lend itself to display of your autointegrate window, but I push it over there to get it out of the way of the processing window. The autointegrate window has grown in size as it has evolved. (so many great options). Is it possible for it to that minimize button that other processes and scripts have? That would make it easier to get it out of the way during running.

**Comment by ricandersonva** [comment]
forgot to say that when I push it over to the smaller display, it grows to twice its size, so when it comes back to the original screen, it is proportionately larger, which I can resize to get it back.

**Comment by jarmoruuth** [comment]
Hi Rick, that minimizing thing certainly sounds useful. I will take a look at it.

Just checking, is it so that when you push the script dialog to a smaller window and then pull it back to the larger display the size has changed? That sounds a bit strange. There is a reset button in the dialog but not sure if it would help in this case. I am on Windows 11 but I have two screens. Maybe I can repeat the problem if I set the other screen to a lower resolution.

Unfortunately fitting the dialog to a screen is a constant problem. And unfortunately I do not yet have a solution to all cases.

Btw, if not already using it, it would be great if you check the test repository https://ruuth.xyz/test/autointegrate/. There are some interface changes and I am not sure how well they work on different systems.

Regards,
Jarmo

**Comment by jarmoruuth** [comment]
Hi Rick, That is PixInsight repository link for automatic updates. If you use the normal repository  https://ruuth.xyz/autointegrate/ then you need to change the link in PixInsight. Or if you use the script directly you can just download it from GitHub.

There is no way to have a minimize button in a script. But I have done something similar. I will post it later today so you can check if that is ok.

Jarmo

**Comment by jarmoruuth** [comment]
Now there is a test version available with a minimize button. It does not actually minimize the dialog but hides most elements to make the dialog small.

Jarmo

**Comment by ricandersonva** [comment]
My first impression is that I like it alot. It does get out of the way during processing. I am running a 20 sub processing right now. I will provide more details on testing tomorrow sometime, but first look is encouraging.

Thanks.
