### ISSUE TITLE
flowchartChildBegin, current node is not parent or child

### ISSUE THREAD

**Issue by agnunez** [jarmoruuth/AutoIntegrate#32]
Thanks for the script. Trying to test it with HSO images, I always receive the following error:

flowchartChildBegin, current node is not parent or child

This is the log:

PixInsight version 1.8.9-2
AutoIntegrate v1.65
Processing date Tue Dec 05 2023 09:24:18 GMT+0100
Processing options:
Fix column defects: true
Fix row defects: true
GC on light images: true
Background neutralization: true
ImageIntegration use SSWEIGHT: true
Crop to common area: true
Keep integrated images: true
Synthetic L: true
Use BlurXTerminator: true
Use NoiseXTerminator: true
Use StarNet2: true
Narrowband mapping: HSO
Narrowband R mapping: H
Narrowband G mapping: S
Narrowband linear fit: None
User selected reference image for filter Ha3 : C:/Users/river/Downloads/Agus/m27/NGC_6853_Ha3_300,000secs_1x1_-20,00C_00003592.fit
Start processing...
Create channel images
Check custom mapping
calibrateEngine, no bias, flat or dark files
Run Linear Defect Detection
Image LDD integration on 8 files
flowchartChildBegin, current node is not parent or child

No further info to correct the error... 

Do I need to add any extra info? Am I missing something?  thanks

**Comment by jarmoruuth** [comment]
Hi,

Thanks for reporting the problem. I have reproduced it. The problem happens when you use 'Fix column defects' or 'Fix row detects' option. 

I have pushed a fix to my PixInsight test repository https://ruuth.xyz/test/autointegrate/. I will push the fix also to the main repository soon but I want to do some more testing before doing it.

Regards,
Jarmo
